# Generated by Django 4.2.3 on 2023-07-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('completion_date', models.DateField()),
                ('unique_code', models.CharField(max_length=100, unique=True)),
                ('selected_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certificatetemplate')),
            ],
        ),
    ]
