# Generated by Django 4.2.3 on 2023-07-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='thumbnail',
            field=models.ImageField(upload_to='certificate_templates/thumbnails/'),
        ),
    ]
