# Generated by Django 4.2.3 on 2023-07-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_certificatetemplate_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='file_path',
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='template_image',
            field=models.ImageField(default='path/to/default/template_image.png', upload_to='frontend/templates/'),
        ),
    ]
